package main

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"os"
	"time"

	sqlitestore "agent-collaboration/go/pkg/store/sqlite"
)

// runSessionRegister ports cmd_session_register from
// scripts/peer-inbox-db.py. Scope now includes label autogen, pair-
// key resolution (--pair-key / --new-pair / preserve), receive-mode,
// home-host federation seed, auth-token mint (v3.3 Item 7), and
// channel-socket pairing via the parent-process walk.
//
// Still deferred (Phase 5.1 backlog): recent-seen-sessions fallback,
// system-event emission on join, stale-marker sweep.
func runSessionRegister(args []string) int {
	fs := flag.NewFlagSet("session-register", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	var (
		cwdFlag     = fs.String("cwd", "", "session cwd (default: process cwd)")
		label       = fs.String("label", "", "session label (autogenerated when omitted)")
		agent       = fs.String("agent", "", "agent id (required): claude|codex|gemini|pi|human")
		role        = fs.String("role", "", "role tag (optional): lead|challenger|mediator|peer|...")
		sessionKey  = fs.String("session-key", "", "session key (explicit override of env discovery)")
		pairKey     = fs.String("pair-key", "", "join an existing pair-key-scoped room")
		newPair     = fs.Bool("new-pair", false, "mint a fresh pair-key slug and print it")
		receiveMode = fs.String("receive-mode", "", "interactive | daemon (Topic 3 §3.4 (b) verb-entry gate)")
		homeHost    = fs.String("home-host", "", "v3.3 federation home host (defaults to AGENT_COLLAB_SELF_HOST / hostname)")
		force       = fs.Bool("force", false, "override idle-collision guard")
	)
	if err := fs.Parse(args); err != nil {
		return exitUsage
	}
	if *agent == "" {
		fmt.Fprintln(os.Stderr, "session-register: --agent is required")
		return exitUsage
	}

	if *pairKey != "" && *newPair {
		fmt.Fprintln(os.Stderr, "session-register: --pair-key and --new-pair are mutually exclusive")
		return exitUsage
	}
	if *pairKey != "" {
		if err := sqlitestore.ValidatePairKey(*pairKey); err != nil {
			fmt.Fprintf(os.Stderr, "session-register: %v\n", err)
			return exitUsage
		}
	}
	if *homeHost != "" {
		if err := sqlitestore.ValidateHostLabel(*homeHost); err != nil {
			fmt.Fprintf(os.Stderr, "session-register: %v\n", err)
			return exitUsage
		}
	}
	if err := sqlitestore.ValidateAgent(*agent); err != nil {
		fmt.Fprintf(os.Stderr, "session-register: %v\n", err)
		return exitUsage
	}

	finalLabel := *label
	if finalLabel == "" {
		// Label autogen mirrors generate_label — adjective-noun.
		// Validation is a post-gen sanity check that the wordlist
		// produces a shape matching LABEL_RE.
		finalLabel = autoLabel()
	}
	if err := sqlitestore.ValidateLabel(finalLabel); err != nil {
		fmt.Fprintf(os.Stderr, "session-register: %v\n", err)
		return exitUsage
	}

	if *receiveMode != "" && *receiveMode != "interactive" && *receiveMode != "daemon" {
		fmt.Fprintf(os.Stderr, "session-register: --receive-mode must be 'interactive' or 'daemon' (got %q)\n", *receiveMode)
		return exitUsage
	}

	resolvedCWD, err := resolveCWD(*cwdFlag)
	if err != nil {
		fmt.Fprintf(os.Stderr, "session-register: resolve cwd: %v\n", err)
		return exitInternal
	}

	// Session-key resolution order: explicit --session-key → env vars
	// (discoverSessionKey) → codex/gemini auto-UUID (when row already
	// exists we reuse, else mint `auto-<agent>-<uuid>`). recent_seen
	// fallback is Phase 4.
	sk := *sessionKey
	if sk == "" {
		sk = discoverSessionKey()
	}
	if sk == "" && (*agent == "codex" || *agent == "gemini") {
		sk = autoAgentSessionKey(resolvedCWD, finalLabel, *agent)
	}
	if sk == "" {
		// Last resort: the UserPromptSubmit hook logs every Claude
		// session_id it sees in this cwd. Pick the newest — matches the
		// Python fallback at cmd_session_register's key-resolution tail.
		if seen := recentSeenSessions(resolvedCWD, 1); len(seen) > 0 {
			sk = seen[0]
		}
	}
	if sk == "" {
		fmt.Fprintln(os.Stderr,
			"session-register: no session key available. Pass --session-key, set "+
				"AGENT_COLLAB_SESSION_KEY, or (for claude) let UserPromptSubmit log "+
				"a session id first.")
		return exitInternal
	}

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	st, err := sqlitestore.Open(ctx)
	if err != nil {
		fmt.Fprintf(os.Stderr, "session-register: open store: %v\n", err)
		return exitInternal
	}
	defer st.Close()

	// Pair with the channel MCP server Claude spawned at session start.
	// Best-effort: silently no-op when no channel is live (e.g. codex /
	// gemini sessions, or a Claude session whose channel exited).
	channelSocket := findPendingChannelSocket()

	res, err := st.RegisterSession(ctx, sqlitestore.SessionRegisterParams{
		CWD: resolvedCWD, Label: finalLabel, Agent: *agent, Role: *role,
		SessionKey: sk, ChannelSocket: channelSocket,
		PairKey: *pairKey, NewPair: *newPair,
		ReceiveMode: *receiveMode, HomeHost: *homeHost, Force: *force,
	})
	if err != nil {
		if errors.Is(err, sqlitestore.ErrLabelCollision) {
			fmt.Fprintf(os.Stderr, "session-register: %v\n", err)
			return 1 // Python EXIT_LABEL_COLLISION
		}
		if errors.Is(err, sqlitestore.ErrHomeHostImmutable) {
			fmt.Fprintf(os.Stderr, "session-register: %v\n", err)
			return exitUsage
		}
		fmt.Fprintf(os.Stderr, "session-register: %v\n", err)
		return exitInternal
	}

	writeMarker(resolvedCWD, finalLabel, sk)
	sweepStaleMarkersForLabel(resolvedCWD, finalLabel, sk)

	role4Print := res.Role
	if role4Print == "" {
		role4Print = "peer"
	}
	channelNote := " [channel: none]"
	if channelSocket != "" {
		channelNote = " [channel: paired]"
	}
	pairNote := ""
	if res.PairKey != "" {
		pairNote = fmt.Sprintf(" [pair_key=%s]", res.PairKey)
	}
	fmt.Printf("registered: %s (%s, %s) at %s [session_key=%s]%s%s\n",
		res.Label, res.Agent, role4Print, res.CWD,
		sessionKeyHash(sk), channelNote, pairNote,
	)
	if res.AuthTokenNew {
		fmt.Printf("auth_token: %s\n", res.AuthToken)
		fmt.Fprintf(os.Stderr,
			"  For cross-host sends from another peer: set an env var (e.g. "+
				"AGENT_COLLAB_TOKEN_%s) to this value and reference it from "+
				"remotes.json as auth_token_env.\n",
			upperEnvTag(sqlitestore.SelfHost()))
	}
	return exitOK
}

// sessionKeyHash mirrors Python's session_key_hash — first 16 hex
// chars of sha256(key). Kept private to this verb; peer-receive/list
// don't need it.
func sessionKeyHash(key string) string {
	sum := sha256.Sum256([]byte(key))
	return hex.EncodeToString(sum[:])[:16]
}

// autoAgentSessionKey reuses the existing row's session_key when the
// (cwd, label) pair already exists (idempotent re-register) and mints
// `auto-<agent>-<uuidv4>` otherwise. Matches Python's codex/gemini
// fallback in cmd_session_register (lines 1636-1654).
//
// Best-effort: if the store probe fails for any reason, returns "" so
// the caller's error path surfaces the "no session key available"
// message rather than a surprising DB error.
func autoAgentSessionKey(cwd, label, agent string) string {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	st, err := sqlitestore.Open(ctx)
	if err != nil {
		return mintAutoKey(agent)
	}
	defer st.Close()
	if existing, err := st.GetSessionKeyForSelf(ctx, cwd, label); err == nil && existing != "" {
		return existing
	}
	return mintAutoKey(agent)
}

// mintAutoKey mirrors Python's `auto-<agent>-<uuid4>` pattern. We emit
// a UUIDv4 with the standard 8-4-4-4-12 dash format so the shape
// matches Python's `uuid.uuid4()` stringification.
func mintAutoKey(agent string) string {
	buf := make([]byte, 16)
	if _, err := rand.Read(buf); err != nil {
		return ""
	}
	buf[6] = (buf[6] & 0x0f) | 0x40 // version 4
	buf[8] = (buf[8] & 0x3f) | 0x80 // variant RFC 4122
	return fmt.Sprintf("auto-%s-%08x-%04x-%04x-%04x-%012x",
		agent,
		buf[0:4], buf[4:6], buf[6:8], buf[8:10], buf[10:16],
	)
}

// autoLabel delegates to the store helper that mirrors Python's
// generate_label (adjective-noun). The Go wordlist is a full copy of
// Python's PAIR_KEY_ADJECTIVES / PAIR_KEY_NOUNS; bumping one without
// the other silently drifts the label space.
func autoLabel() string {
	// GenerateLabel isn't exported to keep the API small; emit via a
	// local helper that forwards to the test-friendly entry point.
	return sqlitestore.NewAutoLabel()
}

// writeMarker writes <cwd>/.agent-collab/sessions/<sha16(key)>.json
// with {"cwd","label","session_key"} so ResolveSelf can find this
// session on subsequent invocations. Idempotent: overwriting with the
// same key is a no-op from ResolveSelf's POV.
//
// Keeps scope minimal: best-effort, warns on failure but doesn't roll
// back the DB row. An operator can re-run session-register to retry.
// Stale-marker sweep stays deferred (Phase 4).
func writeMarker(cwd, label, sessionKey string) {
	sum := sha256.Sum256([]byte(sessionKey))
	name := hex.EncodeToString(sum[:])[:16] + ".json"
	dir := fmt.Sprintf("%s/.agent-collab/sessions", cwd)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "session-register: warning: mkdir %s: %v\n", dir, err)
		return
	}
	path := dir + "/" + name
	body := fmt.Sprintf(`{"cwd": %q, "label": %q, "session_key": %q}`, cwd, label, sessionKey)
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "session-register: warning: write marker %s: %v\n", path, err)
	}
}

// upperEnvTag reproduces Python's .upper() on the host label so the
// stderr hint text matches Python's byte-for-byte.
func upperEnvTag(h string) string {
	// Uppercase in place — the label alphabet is ASCII so a byte-level
	// transform suffices.
	b := []byte(h)
	for i, c := range b {
		if c >= 'a' && c <= 'z' {
			b[i] = c - 32
		}
	}
	return string(b)
}
