// agent-collaboration peer-inbox wire protocol, v1.
//
// This file is the load-bearing artifact for future-language optionality.
// It is exercised under real traffic on the Unix socket from v3.0 day one so
// the spec is production-tested before a cloud server ever accepts it.
//
// Versioning rules (see docs/protocol/v1.md):
//   - Additive fields only. Never renumber. Never change field types.
//   - Deprecations: mark with `[deprecated = true]`; reserve the field number
//     via `reserved N;` after removal.
//   - Breaking changes require a sibling v2.proto file and a new capability
//     negotiation entry.
//
// Generated Go bindings live at `go/pkg/protocol/` and are regenerated via
// `scripts/build-proto.sh`. Generated bindings are the only way transport
// code moves bytes on the wire.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v6.33.1
// source: v1.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope is the outermost wire frame for every peer-inbox message.
//
// Invariants:
//   - `version` MUST equal 1 for this file's schema.
//   - `type` MUST match a payload type declared in this file. Unknown types
//     cause the peer to log + drop (forward-compat behavior for future
//     types that older binaries do not know).
//   - `payload` MUST unpack cleanly to the Go type registered for `type`.
//   - `idempotency_key` MUST be populated by senders on every message, even
//     on the same-machine Unix-socket path, so cross-machine dedup (v2) has
//     a stable key without changing the caller contract.
type Envelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Fully-qualified protobuf type name of the payload, e.g. "agentcollab.v1.PeerSend".
	// Required. Used by receivers to dispatch to the right Go handler without
	// relying on oneof (which breaks forward-compat on exhaustive switches).
	Type    string       `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload *anypb.Any   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Auth    *AuthContext `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	// Caller-populated key for cross-machine dedup (v2). Senders MUST set this
	// on every outbound message. On SQLite (v1), uniqueness is per (workspace_id,
	// idempotency_key). Recommended shape: UUIDv7 or monotonic-client-seq+random.
	IdempotencyKey string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Monotonic per-sender sequence number. Helps receivers detect reordering
	// under cross-machine transport (v2). Unused on Unix socket in v1.
	ClientSeq uint64 `protobuf:"varint,6,opt,name=client_seq,json=clientSeq,proto3" json:"client_seq,omitempty"`
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetAuth() *AuthContext {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Envelope) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Envelope) GetClientSeq() uint64 {
	if x != nil {
		return x.ClientSeq
	}
	return 0
}

// AuthContext carries the sender's identity. In v1, `workspace_id` defaults
// to "default" and `user_id` is empty — the LocalTrust Auth impl accepts any
// combination. In v2, `user_id` is populated from a verified JWT / OIDC token
// and `workspace_id` gates Postgres RLS.
type AuthContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkspaceId  string `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`    // v1: always "default"
	UserId       string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // v1: empty; v2: verified user identifier
	SessionLabel string `protobuf:"bytes,3,opt,name=session_label,json=sessionLabel,proto3" json:"session_label,omitempty"` // sender's peer-inbox label (e.g. "coder")
}

func (x *AuthContext) Reset() {
	*x = AuthContext{}
	mi := &file_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthContext) ProtoMessage() {}

func (x *AuthContext) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthContext.ProtoReflect.Descriptor instead.
func (*AuthContext) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{1}
}

func (x *AuthContext) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *AuthContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthContext) GetSessionLabel() string {
	if x != nil {
		return x.SessionLabel
	}
	return ""
}

// Hello is the first frame on every new Unix-socket connection. Both sides
// exchange Hello before any other message. Version mismatch → disconnect
// with a structured error frame; unknown types in `supported_types` are
// ignored, matching the forward-compat rule for `Envelope.type`.
type Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version        uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	SupportedTypes []string `protobuf:"bytes,2,rep,name=supported_types,json=supportedTypes,proto3" json:"supported_types,omitempty"` // fully-qualified type names this peer handles
	PeerLabel      string   `protobuf:"bytes,3,opt,name=peer_label,json=peerLabel,proto3" json:"peer_label,omitempty"`
	Agent          string   `protobuf:"bytes,4,opt,name=agent,proto3" json:"agent,omitempty"` // "claude" | "codex" | "gemini"
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Hello) GetSupportedTypes() []string {
	if x != nil {
		return x.SupportedTypes
	}
	return nil
}

func (x *Hello) GetPeerLabel() string {
	if x != nil {
		return x.PeerLabel
	}
	return ""
}

func (x *Hello) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

// PeerSend: direct unicast to a named peer.
type PeerSend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToLabel string   `protobuf:"bytes,1,opt,name=to_label,json=toLabel,proto3" json:"to_label,omitempty"`
	ToCwd   string   `protobuf:"bytes,2,opt,name=to_cwd,json=toCwd,proto3" json:"to_cwd,omitempty"` // optional: disambiguates when multiple pairs share labels
	Body    string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                // UTF-8, max 8 KB
	Mention []string `protobuf:"bytes,4,rep,name=mention,proto3" json:"mention,omitempty"`
}

func (x *PeerSend) Reset() {
	*x = PeerSend{}
	mi := &file_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerSend) ProtoMessage() {}

func (x *PeerSend) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerSend.ProtoReflect.Descriptor instead.
func (*PeerSend) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{3}
}

func (x *PeerSend) GetToLabel() string {
	if x != nil {
		return x.ToLabel
	}
	return ""
}

func (x *PeerSend) GetToCwd() string {
	if x != nil {
		return x.ToCwd
	}
	return ""
}

func (x *PeerSend) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PeerSend) GetMention() []string {
	if x != nil {
		return x.Mention
	}
	return nil
}

// PeerBroadcast: fan-out to every live peer in the sender's room.
type PeerBroadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cohort  []string `protobuf:"bytes,1,rep,name=cohort,proto3" json:"cohort,omitempty"` // if present, multicast to named subset
	Body    string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Mention []string `protobuf:"bytes,3,rep,name=mention,proto3" json:"mention,omitempty"`
}

func (x *PeerBroadcast) Reset() {
	*x = PeerBroadcast{}
	mi := &file_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerBroadcast) ProtoMessage() {}

func (x *PeerBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerBroadcast.ProtoReflect.Descriptor instead.
func (*PeerBroadcast) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{4}
}

func (x *PeerBroadcast) GetCohort() []string {
	if x != nil {
		return x.Cohort
	}
	return nil
}

func (x *PeerBroadcast) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PeerBroadcast) GetMention() []string {
	if x != nil {
		return x.Mention
	}
	return nil
}

// PeerReceiveRequest: pulled by the hook on UserPromptSubmit. The response
// is a PeerReceiveResponse with unread messages + a flag indicating whether
// the receiver has already marked-read (claimed) them.
type PeerReceiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MarkRead bool   `protobuf:"varint,1,opt,name=mark_read,json=markRead,proto3" json:"mark_read,omitempty"`
	Since    string `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"` // optional: ISO-8601; only return messages newer than this
}

func (x *PeerReceiveRequest) Reset() {
	*x = PeerReceiveRequest{}
	mi := &file_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerReceiveRequest) ProtoMessage() {}

func (x *PeerReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerReceiveRequest.ProtoReflect.Descriptor instead.
func (*PeerReceiveRequest) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{5}
}

func (x *PeerReceiveRequest) GetMarkRead() bool {
	if x != nil {
		return x.MarkRead
	}
	return false
}

func (x *PeerReceiveRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

type PeerReceiveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*InboxMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *PeerReceiveResponse) Reset() {
	*x = PeerReceiveResponse{}
	mi := &file_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerReceiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerReceiveResponse) ProtoMessage() {}

func (x *PeerReceiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerReceiveResponse.ProtoReflect.Descriptor instead.
func (*PeerReceiveResponse) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{6}
}

func (x *PeerReceiveResponse) GetMessages() []*InboxMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type InboxMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromLabel string `protobuf:"bytes,2,opt,name=from_label,json=fromLabel,proto3" json:"from_label,omitempty"`
	FromCwd   string `protobuf:"bytes,3,opt,name=from_cwd,json=fromCwd,proto3" json:"from_cwd,omitempty"`
	Body      string `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO-8601 UTC
	RoomKey   string `protobuf:"bytes,6,opt,name=room_key,json=roomKey,proto3" json:"room_key,omitempty"`
}

func (x *InboxMessage) Reset() {
	*x = InboxMessage{}
	mi := &file_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxMessage) ProtoMessage() {}

func (x *InboxMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxMessage.ProtoReflect.Descriptor instead.
func (*InboxMessage) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{7}
}

func (x *InboxMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InboxMessage) GetFromLabel() string {
	if x != nil {
		return x.FromLabel
	}
	return ""
}

func (x *InboxMessage) GetFromCwd() string {
	if x != nil {
		return x.FromCwd
	}
	return ""
}

func (x *InboxMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *InboxMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *InboxMessage) GetRoomKey() string {
	if x != nil {
		return x.RoomKey
	}
	return ""
}

// SessionRegister: idempotent registration for a (cwd, label) pair.
type SessionRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label      string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Agent      string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"` // "claude" | "codex" | "gemini"
	Role       string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`   // "lead" | "challenger" | "peer" | "mediator"
	PairKey    string                 `protobuf:"bytes,4,opt,name=pair_key,json=pairKey,proto3" json:"pair_key,omitempty"`
	SessionKey string                 `protobuf:"bytes,5,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	StartedAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
}

func (x *SessionRegister) Reset() {
	*x = SessionRegister{}
	mi := &file_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRegister) ProtoMessage() {}

func (x *SessionRegister) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRegister.ProtoReflect.Descriptor instead.
func (*SessionRegister) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{8}
}

func (x *SessionRegister) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SessionRegister) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *SessionRegister) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SessionRegister) GetPairKey() string {
	if x != nil {
		return x.PairKey
	}
	return ""
}

func (x *SessionRegister) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *SessionRegister) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// Error: a structured failure frame. Senders emit this when they reject an
// inbound frame — e.g., JSON masquerading as Envelope, version mismatch,
// unknown type. Receivers do NOT close the connection on Error; they log.
type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code             string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`       // "invalid_frame" | "version_mismatch" | "unknown_type" | ...
	Message          string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // human-readable
	FrameSizeBytes   uint32 `protobuf:"varint,3,opt,name=frame_size_bytes,json=frameSizeBytes,proto3" json:"frame_size_bytes,omitempty"`
	FirstBytesHex    string `protobuf:"bytes,4,opt,name=first_bytes_hex,json=firstBytesHex,proto3" json:"first_bytes_hex,omitempty"` // first 16 bytes, space-separated hex, for debugging
	ExpectedMagicHex string `protobuf:"bytes,5,opt,name=expected_magic_hex,json=expectedMagicHex,proto3" json:"expected_magic_hex,omitempty"`
	PeerLabel        string `protobuf:"bytes,6,opt,name=peer_label,json=peerLabel,proto3" json:"peer_label,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_v1_proto_rawDescGZIP(), []int{9}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetFrameSizeBytes() uint32 {
	if x != nil {
		return x.FrameSizeBytes
	}
	return 0
}

func (x *Error) GetFirstBytesHex() string {
	if x != nil {
		return x.FirstBytesHex
	}
	return ""
}

func (x *Error) GetExpectedMagicHex() string {
	if x != nil {
		return x.ExpectedMagicHex
	}
	return ""
}

func (x *Error) GetPeerLabel() string {
	if x != nil {
		return x.PeerLabel
	}
	return ""
}

var File_v1_proto protoreflect.FileDescriptor

var file_v1_proto_rawDesc = []byte{
	0x0a, 0x08, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe1, 0x01, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c,
	0x6f, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x2e, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x2f, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x04, 0x61, 0x75,
	0x74, 0x68, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63,
	0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x64, 0x65,
	0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x71, 0x22, 0x6e, 0x0a, 0x0b, 0x41, 0x75,
	0x74, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x6f, 0x72,
	0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x7f, 0x0a, 0x05, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a,
	0x0f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x65, 0x65, 0x72,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x22, 0x6a, 0x0a, 0x08, 0x50,
	0x65, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x5f, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x6f, 0x5f, 0x63, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x43, 0x77, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x55, 0x0a, 0x0d, 0x50, 0x65, 0x65, 0x72, 0x42,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x68, 0x6f,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x68, 0x6f, 0x72, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x47,
	0x0a, 0x12, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x5f, 0x72, 0x65, 0x61,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x61,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x22, 0x4f, 0x0a, 0x13, 0x50, 0x65, 0x65, 0x72, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38,
	0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x62, 0x2e, 0x76,
	0x31, 0x2e, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0xa6, 0x01, 0x0a, 0x0c, 0x49, 0x6e, 0x62,
	0x6f, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x72, 0x6f,
	0x6d, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66,
	0x72, 0x6f, 0x6d, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d,
	0x5f, 0x63, 0x77, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d,
	0x43, 0x77, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x4b, 0x65,
	0x79, 0x22, 0xc8, 0x01, 0x0a, 0x0f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x69, 0x72, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x69, 0x72, 0x4b, 0x65, 0x79,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65,
	0x79, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xd4, 0x01, 0x0a,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x26,
	0x0a, 0x0f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x68, 0x65,
	0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x69, 0x72, 0x73, 0x74, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x48, 0x65, 0x78, 0x12, 0x2c, 0x0a, 0x12, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x5f, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x5f, 0x68, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x4d, 0x61, 0x67, 0x69,
	0x63, 0x48, 0x65, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x65, 0x65, 0x72, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x42, 0x2e, 0x5a, 0x2c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2d, 0x63, 0x6f, 0x6c,
	0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_proto_rawDescOnce sync.Once
	file_v1_proto_rawDescData = file_v1_proto_rawDesc
)

func file_v1_proto_rawDescGZIP() []byte {
	file_v1_proto_rawDescOnce.Do(func() {
		file_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_proto_rawDescData)
	})
	return file_v1_proto_rawDescData
}

var file_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_proto_goTypes = []any{
	(*Envelope)(nil),              // 0: agentcollab.v1.Envelope
	(*AuthContext)(nil),           // 1: agentcollab.v1.AuthContext
	(*Hello)(nil),                 // 2: agentcollab.v1.Hello
	(*PeerSend)(nil),              // 3: agentcollab.v1.PeerSend
	(*PeerBroadcast)(nil),         // 4: agentcollab.v1.PeerBroadcast
	(*PeerReceiveRequest)(nil),    // 5: agentcollab.v1.PeerReceiveRequest
	(*PeerReceiveResponse)(nil),   // 6: agentcollab.v1.PeerReceiveResponse
	(*InboxMessage)(nil),          // 7: agentcollab.v1.InboxMessage
	(*SessionRegister)(nil),       // 8: agentcollab.v1.SessionRegister
	(*Error)(nil),                 // 9: agentcollab.v1.Error
	(*anypb.Any)(nil),             // 10: google.protobuf.Any
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_v1_proto_depIdxs = []int32{
	10, // 0: agentcollab.v1.Envelope.payload:type_name -> google.protobuf.Any
	1,  // 1: agentcollab.v1.Envelope.auth:type_name -> agentcollab.v1.AuthContext
	7,  // 2: agentcollab.v1.PeerReceiveResponse.messages:type_name -> agentcollab.v1.InboxMessage
	11, // 3: agentcollab.v1.SessionRegister.started_at:type_name -> google.protobuf.Timestamp
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_v1_proto_init() }
func file_v1_proto_init() {
	if File_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_proto_goTypes,
		DependencyIndexes: file_v1_proto_depIdxs,
		MessageInfos:      file_v1_proto_msgTypes,
	}.Build()
	File_v1_proto = out.File
	file_v1_proto_rawDesc = nil
	file_v1_proto_goTypes = nil
	file_v1_proto_depIdxs = nil
}
